SUPABASE_URL = "https://aeplqsryvyeahpimvagz.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFlcGxxc3J5dnllYWhwaW12YWd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1Nzg1OTEsImV4cCI6MjA2MjE1NDU5MX0.txx7EeKt6xZy_lbbsWPqXux_aI2Mxvp3XqnaSpZdjOQ"
